service: gaming
plugins:
  - serverless-apigw-binary
  - serverless-offline
provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 192
  timeout: 10
package:
  exclude:
    - ./**
  include:
    - "node_modules/aws-serverless-express/**"
    - "node_modules/binary-case/**"
    - "node_modules/type-is/**"
    - "node_modules/media-typer/**"
    - "node_modules/mime-types/**"
    - "node_modules/mime-db/**"
    - "dist/**"
custom:
  apigwBinary:
    types:
      - "*/*"
functions:
  api:
    handler: src/lambda.handler
    events:
      - http: GET /
